contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #reportho channel"
    url: https://nfcore.slack.com/channels/reportho
    about: Discussion about the nf-core/reportho pipeline
